### ISSUE TITLE
Don't silence original exception

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/rapid-watershed-delineation#16]
Some Hill Slope functions (snapping=0) can trigger an exception here:
https://github.com/WikiWatershed/rapid-watershed-delineation/blob/develop/src/api/main.py#L71-L73

Though the original exception is not reported.  We should preserve that error for debugging.

**Comment by kdeloach** [comment]
Fixed by 45cdc630523c11ff3ed73097d776e7ef5e6a031c?

**Comment by kdeloach** [comment]
I think this has been fixed.
