### ISSUE TITLE
Make ~600GB of data available to RWD worker

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/rapid-watershed-delineation#31]
If #30 succeeds, the next step will be to expand to all NHD regions, which would be composed of about 600GB of uncompressed data.  Evaluate whether our EBS snapshot approach will accomodate this increase and determine if a solution like EFS would do better.

**Comment by kdeloach** [comment]
Where could we find this data set?

**Comment by mmcfarland** [comment]
I hasn't been derived yet, the data in #30 being a test case.  However, we can anticipate that we'll need to accommodate an increasingly large set of data in addition to the existing RWD data to support this second RWD version.

**Comment by kdeloach** [comment]
The primary goal of this task is to establish that we have the ability to use EBS for RWD data. 

While we're waiting on the full 600GB data set, we can upload the current RWD data to EBS, make the necessary modifications to our deployment pipeline, then verify that RWD still works with this arrangement.

**Comment by kdeloach** [comment]
The current RWD data has been copied to an EFS instance.
