### ISSUE TITLE
Test RWD on EFS

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/rapid-watershed-delineation#32]
RWD data has been copied to EFS. Verify that the RWD still works using the mounted EFS drive.

Currently, the worker AMI exists on staging, and is shared with production. Can we do the same thing with EFS?

Follow up to #31

**Comment by kdeloach** [comment]
Blocked by https://github.com/WikiWatershed/model-my-watershed/issues/1521

**Comment by kdeloach** [comment]
The performance difference between using EBS and EFS is negligible. Switching to EFS does not seem worthwhile for our use case, considering the amount of effort it will take to create and maintain EFS volumes for each AWS account (and stack), not to mention the additional billings that will result from using additional resources.

Steps taken to test EFS:

* Create EFS volume and copy RWD data (using a temporary EC2 instance)
* Create inbound/outbound NFS exceptions in worker security group
* Set desired worker instances to 1 in worker AGS
* Mount EFS inside worker instance (mounting instructions are provided via EFS dashboard)
* Change `mmw-rwd` upstart configuration to use EFS mount instead of `/opt/rwd-data` and restart service
* Test RWD service either by using `curl` on the worker instance, or through the web app

**Comment by mmcfarland** [comment]
Given that the use case is potentially 600GB as described in #31, does that make it a more compelling case or do you think the current setup can handle that?  How do you think the data loading time would be affected when new workers are spun up?

**Comment by kdeloach** [comment]
I think our current setup will be able to handle 600GB fine.

Worker launch time does not appear to be impacted by the size of attached volumes. This is speculation, but the raw bytes for data on EBS volumes restored from a snapshot are copied from S3 on-demand. Which would explain why RWD runs slow and times out frequently on a fresh stack, and becomes faster the more it's used. The benefit to this is that launching instances is quick.

Performance wise, the difference between using EFS and EBS volumes seems negligible. Considering RWD algorithm is not IO-intensive and the data set is mainly static, we aren't able to take advantage of the distribution and scaling properties of EFS.

Price wise, EFS is more expensive.

EFS @ $0.30/GB-month * 2 instances (staging + production) * 600GB = $360/month
EBS @ $0.10/GB-month * 4 workers (staging + production) * 600GB = $240/month

For our current situation, I think just using EBS is the best approach.
