### ISSUE TITLE
Verify NHD EPSG projection

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/rapid-watershed-delineation#39]
We are presently using [EPSG 5070](https://epsg.io/5070) "NAD83 / Conus Albers" to reproject NHD points to WGS84 ([here](https://github.com/WikiWatershed/rapid-watershed-delineation/blob/develop/src/api/main.py#L116) and [here](https://github.com/WikiWatershed/rapid-watershed-delineation/blob/develop/src/api/main.py#L144)).

However, closer inspection of the main NHD shapefile reveals that the projection is "NAD_1983_Albers" / "Albers_Conic_Equal_Area". 

[EPSG 102008](https://epsg.io/102008) "North America Albers Equal Area Conic" seems to be a closer match.

```
> ogrinfo -so /media/passport/rwd-nhd/Main_Watershed/gw.shp gw
INFO: Open of `/media/passport/rwd-nhd/Main_Watershed/gw.shp'
      using driver `ESRI Shapefile' successful.

Layer name: gw
Geometry: Polygon
Feature Count: 4857
Extent: (1350615.000000, 1687605.000000) - (1990125.000000, 2720895.000000)
Layer SRS WKT:
PROJCS["NAD_1983_Albers",
    GEOGCS["GCS_North_American_1983",
        DATUM["North_American_Datum_1983",
            SPHEROID["GRS_1980",6378137.0,298.257222101]],
        PRIMEM["Greenwich",0.0],
        UNIT["Degree",0.0174532925199433]],
    PROJECTION["Albers_Conic_Equal_Area"],
    PARAMETER["false_easting",0.0],
    PARAMETER["false_northing",0.0],
    PARAMETER["longitude_of_center",-96.0],
    PARAMETER["standard_parallel_1",29.5],
    PARAMETER["standard_parallel_2",45.5],
    PARAMETER["latitude_of_center",23.0],
    UNIT["Meter",1.0],
    VERTCS["Unknown VCS",
        VDATUM["Unknown"],
        PARAMETER["Vertical_Shift",0.0],
        PARAMETER["Direction",1.0],
        UNIT["User_Defined_Unit",0.01]]]
GRIDCODE: Integer (10.0)
```

**Comment by dtarb** [comment]
I do not think this is equivalent to EPSG 102008.  The latitude_of_center is different.  https://epsg.io/102008 has 40 degrees.  The text above has 23 degrees.  I was able to find 7301  http://spatialreference.org/ref/sr-org/7301/ that appears to be the same at the text above.

**Comment by ajrobbins** [comment]
Also from David:
>Attached is the gdalinfo output from an NHDPlus Grid.  This shows the projection coordinates but does not give an EPSG code. In ArcGIS the parameters of this projection seem the same as what ESRI names “NAD 1983 Contiguous USA Albers” but different from “North America Albers Equal Area Conic”.
[fdrgdalinfo.txt](https://github.com/WikiWatershed/rapid-watershed-delineation/files/578523/fdrgdalinfo.txt)

**Comment by mmcfarland** [comment]
We're currently using the `OGRSpatialReference.ImportFromEPSG` function to reproject, since we had an (incorrect) EPSG code.  Since the projection @dtarb found is not EPSG, we'll have to update the method.  There is an `importFromWkt` method as well, and the `7301` code has an OGC WKT declaration of:

```
PROJCS["USA_Contiguous_Albers_Equal_Area_Conic_USGS_version",GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Albers"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-96.0],PARAMETER["Standard_Parallel_1",29.5],PARAMETER["Standard_Parallel_2",45.5],PARAMETER["Latitude_Of_Origin",23.0],UNIT["Meter",1]]
```
Ref: http://spatialreference.org/ref/sr-org/7301/ogcwkt/

**Comment by dtarb** [comment]
I confirmed with Arianna in email that EPSG 5070 appears to be the same and agree with using it (at least seeing if it works).  That should simplify/reduce code changes needed.
