### ISSUE TITLE
Round geojson data to significant figures

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/rapid-watershed-delineation#72]
For smaller payloads, round the result geojson lat/lngs to 4 or 5 digits of precision.

**Comment by kellyi** [comment]
> For smaller payloads

What's a good threshold for this? Should it be based on the number of points in the polygon or the area of the shape?

**Comment by mmcfarland** [comment]
It's more about trimming precision that's not necessary for the coordinate, reducing the payload size.  A max of 5 digits after the decimal point was suggested, RWD currently 14 digits of precision.  Based on the lat/lngs of N. America, we should confirm that the proposed reduction in precision doesn't shift the shape too much.

**Comment by mmcfarland** [comment]
> For smaller payloads

That was meant to imply "To create smaller payloads"

**Comment by kellyi** [comment]
That makes sense -- I'll start out truncating to 5 to offer some comparisons.

**Comment by mmcfarland** [comment]
I don't think we need to add this as a dependency, but an implementation can be found:

https://github.com/perrygeo/geojson-precision

**Comment by mmcfarland** [comment]
Additionally, since we're using OGR to convert formats (and simplify), we can probably use an additional command option to only generate the precision we want:  `-co "COORDINATE_PRECISION=6"`

**Comment by kellyi** [comment]
Tried out `-co COORDINATE_PRECISION=5` and kept encountering this error message:

```
driver GeoJSON does not support creation option COORDINATE_PRECISION
```

So I'm going to use a simplified version of how `geojson_precision` works.

**Comment by kellyi** [comment]
This PR has RWD output representing a multipolygon to use to confirm that multipolygon coordinates have the precision changed too.

**Comment by mmcfarland** [comment]
Sorry, I hastily advised `-co` (creation option), but it's really `-lco` (layer creation option) if you want to use that feature. As an example, I've verified the follow `ogr2ogr` cmd augmentation accurately reduces the precision.

```python
cmd = cmd + ['-lco', 'COORDINATE_PRECISION=5']
```
